version: '3.8'

# remove <none>
#docker rmi $(docker images -f "dangling=true" -q)

services:
    data:
        container_name: sqlserver
        image: mcr.microsoft.com/mssql/server:latest
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=yourStrongPassword12!@
        volumes:
            - sqldata:/var/opt/mssql
        networks:
            - pazar-network

    messages:
        container_name: rabbitmq
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        hostname: 'rabbitmq'
        environment:
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
        volumes:
            - rabbitmq:/var/lib/rabbitmq/mnesia
            # - rabbitmq/logs:/var/log/rabbitmq/log
        networks:
            - pazar-network
            
            
        statistics:
        container_name: statistics
        image: mkovachev/pazar-statistics-service
        build:
            context: ./Server
            dockerfile: ./Pazar.Statistics/Dockerfile
        ports:
            - '5004:80'
        env_file:
            - Server/Pazar.Core/Common.env
        environment:
             - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Pazar.Ads;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - ConnectionStrings__CronJobsConnection=Server=sqlserver;Database=PazarAdsCronJobsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=guest
            - MessageQueueSettings__Password=guest
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks:
              - pazar-network
        depends_on:
            - data
            - messages

    identity:
        container_name: identity
        image: mkovachev/pazar-identity
        build:
            context: ./Server
            dockerfile: ./Pazar.Identity/Dockerfile
        ports:
            - '5001:80'
        env_file:
            - Server/Pazar.Core/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Pazar.Identity;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - IdentitySettings__AdminPassword=admin1234
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks:
            - pazar-network
        depends_on:
            - data

    ads:
        container_name: ads
        image: mkovachev/pazar-ads
        build:
            context: ./Server
            dockerfile: ./Pazar.Ads/Dockerfile
        ports:
            - '5002:80'
        env_file:
            - Server/Pazar.Core/Common.env
        environment:
            - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=Pazar.Ads;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - ConnectionStrings__CronJobsConnection=Server=sqlserver;Database=PazarAdsCronJobsDatabase;User Id=sa; Password=yourStrongPassword12!@;MultipleActiveResultSets=true
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=guest
            - MessageQueueSettings__Password=guest
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks:
            - pazar-network
        depends_on:
            - data
            - messages

    watchdog:
        container_name: watchdog
        image: mkovachev/pazar-watchdog
        build:
            context: ./Server
            dockerfile: ./Pazar.Watchdog/Dockerfile
        ports:
            - '5500:80'
        environment:
            - HealthChecks-UI__HealthChecks__0__Name=Identity
            - HealthChecks-UI__HealthChecks__0__Uri=http://identity/health
            - HealthChecks-UI__HealthChecks__1__Name=Ads
            - HealthChecks-UI__HealthChecks__1__Uri=http://ads/health
            - HealthChecks-UI__HealthChecks__2__Name=Notifications
            - HealthChecks-UI__HealthChecks__2__Uri=http://notifications/health
        restart: on-failure
        networks:
            - pazar-network
        depends_on:
            - identity
            - ads
            - notifications

    notifications:
        container_name: notifications
        image: mkovachev/pazar-notifications
        build:
            context: ./Server
            dockerfile: ./Pazar.Notifications/Dockerfile
        ports:
            - '5004:80'
        env_file:
            - Server/Pazar.Core/Common.env
        environment:
            - NotificationSettings__AllowedOrigins=http://localhost
            - MessageQueueSettings__Host=rabbitmq
            - MessageQueueSettings__UserName=guest
            - MessageQueueSettings__Password=guest
        restart: on-failure
        volumes:
            - data-protection:/root/.aspnet/DataProtection-Keys
        networks:
            - pazar-network
        depends_on:
            - messages

    client:
        container_name: client
        image: mkovachev/pazar-client
        build:
            context: ./Client
            dockerfile: ./Dockerfile
            args:
                configuration: development
        ports:
            - '81:80'
        restart: on-failure

        depends_on:
            - identity
            - ads
        networks:
            - pazar-network
        depends_on:
            - identity
            - ads
            - notifications

networks:
    pazar-network:
        name: pazar-network

volumes:
    sqldata:
    rabbitmq:
    data-protection:
